const TRANSLATIONS = {
  en: {
    // Header
    nav_dashboard: 'Dashboard',
    nav_services: 'Services',
    nav_pricing: 'Pricing',
    nav_register: 'Register Free',
    nav_login: 'Sign In',
    live_badge: 'LIVE DATA',

    // Hero
    hero_tag: 'AI-Powered Intelligence',
    hero_title_1: 'Southeast Asia',
    hero_title_2: 'Property Signals',
    hero_desc: 'Real-time market intelligence powered by AI — tracking buyer intent, seller stress, and momentum across 6 SEA markets daily.',
    hero_explore: 'Explore Markets →',
    hero_pricing: 'See Pricing',

    // Stats
    stat_signals: 'Total Signals',
    stat_buyer: 'Buyer Intent',
    stat_seller: 'Seller Stress',
    stat_momentum: 'Momentum',

    // AI section
    ai_title: 'AI-Powered Market Analysis',
    ai_desc: 'Our advanced AI engine processes millions of data points in real-time, delivering actionable insights into Southeast Asia\'s most dynamic property markets.',
    ai_f1: 'Real-time buyer intent tracking',
    ai_f2: 'Seller stress indicators',
    ai_f3: 'Market momentum analysis',
    ai_f4: 'Geographic market insights',
    ai_f5: 'Daily automated data refresh',

    // Cities
    cities_title: 'Southeast Asia\'s Premier Markets',
    cities_desc: 'Comprehensive coverage across the region\'s most dynamic real estate markets',

    // How it works
    how_title: 'How It Works',
    how_desc: 'Three steps from raw web data to actionable market intelligence',
    how_1_title: 'We Scan',
    how_1_desc: 'Our autonomous pipeline scans PropertyGuru, 99.co, Rumah123, DDProperty, Lamudi, Batdongsan and many more — daily across all 6 SEA markets.',
    how_2_title: 'Our AI Classifies',
    how_2_desc: 'Our AI processes every data point — extracting sentiment, scoring momentum, identifying hot zones, and generating market narratives automatically.',
    how_3_title: 'You Act',
    how_3_desc: 'Receive clear, prioritised signals straight to your dashboard so you can identify leads, spot trends, and move faster than competitors.',

    // CTA banner
    cta_title: 'Ready to get started?',
    cta_desc: 'Explore our plans or learn about the intelligence tools powering the platform.',
    cta_pricing: 'See Pricing',
    cta_services: 'Our Services',

    // Footer
    footer_about_title: 'About SEA Property Pulse',
    footer_about_desc: 'Premium AI-powered real estate market intelligence for Southeast Asia. Tracking buyer intent, seller stress, and momentum signals across 6 major markets daily.',
    footer_markets_title: 'Markets Covered',
    footer_contact_title: 'Contact',
    footer_copyright: '© 2026 SEA Property Pulse. All rights reserved.',
    footer_disclaimer: 'The information provided on this platform is for general informational purposes only and does not constitute financial, legal, or investment advice. Tang88 Resources makes no representations or warranties regarding the accuracy or completeness of the data. Users should conduct their own due diligence before making any property investment decisions.',

    // Pricing page
    pricing_tag: 'Pricing',
    pricing_title_1: 'Simple,',
    pricing_title_2: 'Transparent Pricing',
    pricing_desc: 'Start free with no commitment. Scale up as your business grows across SEA markets.',
    free_note: 'All prices in SGD. Starter and above billed monthly. Cancel anytime.',
    featured_badge: 'Most Popular',
    compare_title: 'Plan Comparison',
    faq_title: 'Frequently Asked Questions',
    cta_start: 'Ready to start?',
    cta_start_desc: 'Sign up free — no credit card needed. Upgrade when you\'re ready.',
    cta_start_btn: 'Get Started Free →',
    tier_free: 'Free', tier_starter: 'Starter', tier_growth: 'Growth', tier_pro: 'Pro', tier_enterprise: 'Enterprise',
    forever: 'forever', per_month: '/ month',
    free_desc: 'Try the platform with no commitment. Registration is free — no credit card required.',
    starter_desc: 'For individual agents who want a daily edge in their core markets.',
    growth_desc: 'For active agencies covering multiple SEA markets with daily intelligence needs.',
    pro_desc: 'For power users who need real-time signals and hourly market pulse.',
    enterprise_desc: 'Unlimited markets, real-time feeds, and custom data integrations for large teams.',
    get_started_free: 'Get Started Free',
    get_started: 'Get Started',
    contact_us: 'Contact Us',
    nav_title: 'Navigation',

    // Services page
    services_tag: 'Special Services',
    services_title_1: 'Enterprise Web',
    services_title_2: 'Intelligence Tools',
    services_desc: 'Our platform is powered by a suite of best-in-class web data tools — delivering accurate, real-time property signals across Southeast Asia at scale.',
    active_label: 'Active',
    coming_soon: 'Coming Soon',
    roadmap_label: 'Roadmap',
    pipeline_title: 'How the Pipeline Works',
    pipeline_desc: 'Every tool plays a role in delivering accurate, real-time intelligence to your dashboard.',
    services_cta_title: 'Want access to these tools?',
    services_cta_desc: 'Available as add-ons for Growth, Pro, and Enterprise plans. Contact us to discuss your requirements.',
    contact_us_btn: 'Contact Us →',

    // Register page
    reg_title: 'Create your account',
    reg_have_account: 'Already have an account?',
    reg_signin: 'Sign in',
    reg_name: 'Full name',
    reg_name_ph: 'Your full name',
    reg_email: 'Email address',
    reg_email_ph: 'you@example.com',
    reg_password: 'Password',
    reg_password_ph: 'Min. 8 characters',
    reg_market: 'Choose your market',
    reg_market_ph: 'Select 1 market',
    reg_terms: 'I agree to the Terms of Service and Privacy Policy. I understand this is a free account with 1 market and weekly scans.',
    reg_btn: 'Create free account',
    reg_more_markets: 'Want more markets?',
    reg_see_plans: 'See paid plans',
    reg_left_title_1: 'Start tracking',
    reg_left_title_2: 'your market',
    reg_left_title_3: 'for free.',
    reg_left_desc: 'Get weekly AI-powered property signals for your chosen SEA market — no credit card, no commitment.',
    reg_f1: '1 SEA market of your choice',
    reg_f2: 'Weekly automated scan',
    reg_f3: 'Buyer intent & seller stress signals',
    reg_f4: 'AI market summary delivered to you',
    reg_success_title: 'Check your inbox',
    reg_success_desc1: 'We\'ve sent a confirmation link to',
    reg_success_desc2: 'Click the link to verify your account. Once confirmed, your first weekly market summary will arrive on Sunday.',
    reg_back: '← Back to dashboard',
    err_name: 'Please enter your name',
    err_email: 'Please enter a valid email',
    err_password: 'Password must be at least 8 characters',
    err_market: 'Please choose a market',
    err_terms: 'Please agree to the Terms of Service to continue.',
  },

  ms: {
    nav_dashboard: 'Papan Pemuka',
    nav_services: 'Perkhidmatan',
    nav_pricing: 'Harga',
    nav_register: 'Daftar Percuma',
    nav_login: 'Log Masuk',
    live_badge: 'DATA LANGSUNG',
    hero_tag: 'Kecerdasan Dikuasai AI',
    hero_title_1: 'Asia Tenggara',
    hero_title_2: 'Isyarat Hartanah',
    hero_desc: 'Perisikan pasaran masa nyata dikuasai AI — menjejaki niat pembeli, tekanan penjual, dan momentum merentas 6 pasaran SEA setiap hari.',
    hero_explore: 'Terokai Pasaran →',
    hero_pricing: 'Lihat Harga',
    stat_signals: 'Jumlah Isyarat',
    stat_buyer: 'Niat Pembeli',
    stat_seller: 'Tekanan Penjual',
    stat_momentum: 'Momentum',
    ai_title: 'Analisis Pasaran Dikuasai AI',
    ai_desc: 'Enjin AI canggih kami memproses berjuta titik data secara masa nyata, memberikan pandangan yang boleh diambil tindakan tentang pasaran hartanah Asia Tenggara yang paling dinamik.',
    ai_f1: 'Penjejakan niat pembeli masa nyata',
    ai_f2: 'Petunjuk tekanan penjual',
    ai_f3: 'Analisis momentum pasaran',
    ai_f4: 'Pandangan pasaran geografi',
    ai_f5: 'Penyegaran data automatik harian',
    cities_title: 'Pasaran Utama Asia Tenggara',
    cities_desc: 'Liputan komprehensif merentas pasaran hartanah yang paling dinamik di rantau ini',
    how_title: 'Cara Ia Berfungsi',
    how_desc: 'Tiga langkah dari data web mentah kepada perisikan pasaran yang boleh diambil tindakan',
    how_1_title: 'Kami Mengimbas',
    how_1_desc: 'Saluran paip autonomi kami mengimbas PropertyGuru, 99.co, Rumah123, DDProperty, Lamudi, Batdongsan dan banyak lagi — setiap hari merentas semua 6 pasaran SEA.',
    how_2_title: 'AI Kami Mengklasifikasi',
    how_2_desc: 'AI kami memproses setiap titik data — mengekstrak sentimen, menilai momentum, mengenal pasti zon panas, dan menjana naratif pasaran secara automatik.',
    how_3_title: 'Anda Bertindak',
    how_3_desc: 'Terima isyarat yang jelas dan diprioritikan terus ke papan pemuka anda supaya anda boleh mengenal pasti petunjuk, mengesan trend, dan bergerak lebih pantas daripada pesaing.',
    cta_title: 'Bersedia untuk bermula?',
    cta_desc: 'Terokai pelan kami atau ketahui tentang alat perisikan yang menjanakan platform.',
    cta_pricing: 'Lihat Harga',
    cta_services: 'Perkhidmatan Kami',
    footer_about_title: 'Tentang SEA Property Pulse',
    footer_about_desc: 'Perisikan pasaran hartanah berkuasa AI premium untuk Asia Tenggara. Menjejaki isyarat niat pembeli, tekanan penjual, dan momentum merentas 6 pasaran utama setiap hari.',
    footer_markets_title: 'Pasaran Diliputi',
    footer_contact_title: 'Hubungi',
    footer_copyright: '© 2026 SEA Property Pulse. Hak cipta terpelihara.',
    footer_disclaimer: 'Maklumat yang disediakan di platform ini adalah untuk tujuan maklumat umum sahaja dan tidak merupakan nasihat kewangan, undang-undang, atau pelaburan. Tang88 Resources tidak membuat sebarang representasi atau jaminan mengenai ketepatan atau kesempurnaan data.',
    pricing_tag: 'Harga',
    pricing_title_1: 'Harga',
    pricing_title_2: 'Mudah & Telus',
    pricing_desc: 'Mulakan percuma tanpa komitmen. Naik taraf apabila perniagaan anda berkembang.',
    free_note: 'Semua harga dalam SGD. Starter dan ke atas dibilkan bulanan. Batal bila-bila masa.',
    featured_badge: 'Paling Popular',
    compare_title: 'Perbandingan Pelan',
    faq_title: 'Soalan Lazim',
    cta_start: 'Bersedia untuk bermula?',
    cta_start_desc: 'Daftar percuma — tiada kad kredit diperlukan.',
    cta_start_btn: 'Mulakan Percuma →',
    tier_free: 'Percuma', tier_starter: 'Pemula', tier_growth: 'Pertumbuhan', tier_pro: 'Pro', tier_enterprise: 'Perusahaan',
    forever: 'selamanya', per_month: '/ bulan',
    free_desc: 'Cuba platform tanpa komitmen. Pendaftaran percuma — tiada kad kredit diperlukan.',
    starter_desc: 'Untuk ejen individu yang mahukan kelebihan harian dalam pasaran teras mereka.',
    growth_desc: 'Untuk agensi aktif yang meliputi pelbagai pasaran SEA dengan keperluan perisikan harian.',
    pro_desc: 'Untuk pengguna kuasa yang memerlukan isyarat masa nyata dan denyutan pasaran setiap jam.',
    enterprise_desc: 'Pasaran tanpa had, suapan masa nyata, dan integrasi data tersuai untuk pasukan besar.',
    get_started_free: 'Mulakan Percuma',
    get_started: 'Mulakan',
    contact_us: 'Hubungi Kami',
    nav_title: 'Navigasi',
    services_tag: 'Perkhidmatan Khas',
    services_title_1: 'Alat Perisikan Web',
    services_title_2: 'Peringkat Perusahaan',
    services_desc: 'Platform kami dikuasai oleh suite alat data web terbaik — memberikan isyarat hartanah yang tepat dan masa nyata merentas Asia Tenggara pada skala.',
    active_label: 'Aktif',
    coming_soon: 'Akan Datang',
    roadmap_label: 'Peta Jalan',
    pipeline_title: 'Cara Saluran Paip Berfungsi',
    pipeline_desc: 'Setiap alat memainkan peranan dalam memberikan perisikan masa nyata yang tepat ke papan pemuka anda.',
    services_cta_title: 'Mahu akses kepada alat ini?',
    services_cta_desc: 'Tersedia sebagai tambahan untuk pelan Growth, Pro, dan Enterprise.',
    contact_us_btn: 'Hubungi Kami →',
    reg_title: 'Cipta akaun anda',
    reg_have_account: 'Sudah mempunyai akaun?',
    reg_signin: 'Log masuk',
    reg_name: 'Nama penuh',
    reg_name_ph: 'Nama penuh anda',
    reg_email: 'Alamat e-mel',
    reg_email_ph: 'anda@contoh.com',
    reg_password: 'Kata laluan',
    reg_password_ph: 'Min. 8 aksara',
    reg_market: 'Pilih pasaran anda',
    reg_market_ph: 'Pilih 1 pasaran',
    reg_terms: 'Saya bersetuju dengan Terma Perkhidmatan dan Dasar Privasi. Saya faham ini adalah akaun percuma dengan 1 pasaran dan imbasan mingguan.',
    reg_btn: 'Cipta akaun percuma',
    reg_more_markets: 'Mahu lebih pasaran?',
    reg_see_plans: 'Lihat pelan berbayar',
    reg_left_title_1: 'Mula menjejaki',
    reg_left_title_2: 'pasaran anda',
    reg_left_title_3: 'secara percuma.',
    reg_left_desc: 'Dapatkan isyarat hartanah berkuasa AI mingguan untuk pasaran SEA pilihan anda — tiada kad kredit, tiada komitmen.',
    reg_f1: '1 pasaran SEA pilihan anda',
    reg_f2: 'Imbasan automatik mingguan',
    reg_f3: 'Isyarat niat pembeli & tekanan penjual',
    reg_f4: 'Ringkasan pasaran AI dihantar kepada anda',
    reg_success_title: 'Semak peti masuk anda',
    reg_success_desc1: 'Kami telah menghantar pautan pengesahan ke',
    reg_success_desc2: 'Klik pautan untuk mengesahkan akaun anda. Setelah disahkan, ringkasan pasaran mingguan pertama anda akan tiba pada hari Ahad.',
    reg_back: '← Kembali ke papan pemuka',
    err_name: 'Sila masukkan nama anda',
    err_email: 'Sila masukkan e-mel yang sah',
    err_password: 'Kata laluan mesti sekurang-kurangnya 8 aksara',
    err_market: 'Sila pilih pasaran',
    err_terms: 'Sila bersetuju dengan Terma Perkhidmatan untuk meneruskan.',
  },

  zh: {
    nav_dashboard: '数据面板',
    nav_services: '服务',
    nav_pricing: '价格',
    nav_register: '免费注册',
    nav_login: '登录',
    live_badge: '实时数据',
    hero_tag: 'AI 驱动的智能',
    hero_title_1: '东南亚',
    hero_title_2: '房产信号',
    hero_desc: 'AI 驱动的实时市场情报 — 每日追踪东南亚六大市场的买家意向、卖家压力和市场动能。',
    hero_explore: '探索市场 →',
    hero_pricing: '查看价格',
    stat_signals: '信号总数',
    stat_buyer: '买家意向',
    stat_seller: '卖家压力',
    stat_momentum: '市场动能',
    ai_title: 'AI 驱动的市场分析',
    ai_desc: '我们先进的 AI 引擎实时处理数百万个数据点，为东南亚最具活力的房产市场提供可操作的洞察。',
    ai_f1: '实时买家意向追踪',
    ai_f2: '卖家压力指标',
    ai_f3: '市场动能分析',
    ai_f4: '地理市场洞察',
    ai_f5: '每日自动数据更新',
    cities_title: '东南亚主要市场',
    cities_desc: '全面覆盖该地区最具活力的房地产市场',
    how_title: '运作方式',
    how_desc: '从原始网络数据到可操作市场情报的三个步骤',
    how_1_title: '我们扫描',
    how_1_desc: '我们的自主管道每日扫描 PropertyGuru、99.co、Rumah123、DDProperty、Lamudi、Batdongsan 等平台 — 覆盖全部 6 个东南亚市场。',
    how_2_title: 'AI 分类',
    how_2_desc: '我们的 AI 处理每个数据点 — 提取情感、评分动能、识别热点区域，并自动生成市场叙述。',
    how_3_title: '您行动',
    how_3_desc: '接收清晰、优先级排序的信号直达您的面板，让您识别潜在客户、发现趋势，并比竞争对手更快行动。',
    cta_title: '准备好开始了吗？',
    cta_desc: '探索我们的方案或了解驱动平台的情报工具。',
    cta_pricing: '查看价格',
    cta_services: '我们的服务',
    footer_about_title: '关于 SEA Property Pulse',
    footer_about_desc: '面向东南亚的高级 AI 驱动房地产市场情报。每日追踪六大主要市场的买家意向、卖家压力和动能信号。',
    footer_markets_title: '覆盖市场',
    footer_contact_title: '联系我们',
    footer_copyright: '© 2026 SEA Property Pulse。保留所有权利。',
    footer_disclaimer: '本平台提供的信息仅供一般参考之用，不构成财务、法律或投资建议。Tang88 Resources 对数据的准确性或完整性不作任何陈述或保证。',
    pricing_tag: '价格',
    pricing_title_1: '简单',
    pricing_title_2: '透明定价',
    pricing_desc: '免费开始，无需承诺。随着业务在东南亚市场的增长而升级。',
    free_note: '所有价格以新加坡元计。Starter 及以上按月计费。随时取消。',
    featured_badge: '最受欢迎',
    compare_title: '方案对比',
    faq_title: '常见问题',
    cta_start: '准备好开始了吗？',
    cta_start_desc: '免费注册 — 无需信用卡。准备好后再升级。',
    cta_start_btn: '免费开始 →',
    tier_free: '免费', tier_starter: '入门', tier_growth: '成长', tier_pro: '专业', tier_enterprise: '企业',
    forever: '永久', per_month: '/ 月',
    free_desc: '无需承诺即可试用平台。注册免费 — 无需信用卡。',
    starter_desc: '适合希望在核心市场获得每日优势的个人经纪人。',
    growth_desc: '适合需要每日情报覆盖多个东南亚市场的活跃机构。',
    pro_desc: '适合需要实时信号和每小时市场脉搏的高级用户。',
    enterprise_desc: '无限市场、实时数据流和大型团队的定制数据集成。',
    get_started_free: '免费开始',
    get_started: '开始使用',
    contact_us: '联系我们',
    nav_title: '导航',
    services_tag: '特别服务',
    services_title_1: '企业级网络',
    services_title_2: '情报工具',
    services_desc: '我们的平台由一套最佳网络数据工具驱动 — 大规模提供东南亚准确的实时房产信号。',
    active_label: '活跃',
    coming_soon: '即将推出',
    roadmap_label: '路线图',
    pipeline_title: '管道运作方式',
    pipeline_desc: '每个工具在将准确的实时情报传递到您的面板中都发挥着作用。',
    services_cta_title: '想要访问这些工具？',
    services_cta_desc: '可作为 Growth、Pro 和 Enterprise 方案的附加服务。联系我们讨论您的需求。',
    contact_us_btn: '联系我们 →',
    reg_title: '创建您的账户',
    reg_have_account: '已有账户？',
    reg_signin: '登录',
    reg_name: '全名',
    reg_name_ph: '您的全名',
    reg_email: '电子邮件地址',
    reg_email_ph: 'you@example.com',
    reg_password: '密码',
    reg_password_ph: '至少 8 个字符',
    reg_market: '选择您的市场',
    reg_market_ph: '选择 1 个市场',
    reg_terms: '我同意服务条款和隐私政策。我了解这是一个拥有 1 个市场和每周扫描的免费账户。',
    reg_btn: '创建免费账户',
    reg_more_markets: '想要更多市场？',
    reg_see_plans: '查看付费方案',
    reg_left_title_1: '开始追踪',
    reg_left_title_2: '您的市场',
    reg_left_title_3: '完全免费。',
    reg_left_desc: '获取您选择的东南亚市场的每周 AI 驱动房产信号 — 无需信用卡，无需承诺。',
    reg_f1: '1 个您选择的东南亚市场',
    reg_f2: '每周自动扫描',
    reg_f3: '买家意向和卖家压力信号',
    reg_f4: 'AI 市场摘要直接发送给您',
    reg_success_title: '请查收您的邮箱',
    reg_success_desc1: '我们已向以下地址发送了确认链接',
    reg_success_desc2: '点击链接验证您的账户。确认后，您的第一份每周市场摘要将于周日送达。',
    reg_back: '← 返回数据面板',
    err_name: '请输入您的姓名',
    err_email: '请输入有效的电子邮件',
    err_password: '密码至少需要 8 个字符',
    err_market: '请选择一个市场',
    err_terms: '请同意服务条款以继续。',
  }
};

function getLang() {
  return localStorage.getItem('sea_lang') || 'en';
}

function setLang(lang) {
  localStorage.setItem('sea_lang', lang);
  applyLang(lang);
  updateLangButtons(lang);
}

function t(key) {
  const lang = getLang();
  return TRANSLATIONS[lang][key] || TRANSLATIONS['en'][key] || key;
}

function applyLang(lang) {
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    const attr = el.getAttribute('data-i18n-attr');
    const val = TRANSLATIONS[lang][key] || TRANSLATIONS['en'][key] || key;
    if (attr) {
      el.setAttribute(attr, val);
    } else {
      el.innerHTML = val;
    }
  });
}

function updateLangButtons(lang) {
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });
}

function initLang() {
  const lang = getLang();
  applyLang(lang);
  updateLangButtons(lang);
}

document.addEventListener('DOMContentLoaded', initLang);
